### ISSUE TITLE
Not usable since published without a suitable license

### ISSUE THREAD

**Issue by tim-seoss** [dbrgn/sht2x-rs#1]
Hello,

I'd like to use this code (and carry on development of it - I have a number of SHT21 which I'd like to use in a couple of projects), but there's no license currently.  According to https://choosealicense.com/no-permission/ if there's no license, then:

"Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose."

I wonder if you'd mind licensing it?  The information at https://choosealicense.com/ might be useful.

FWIW, the rust embedded-hal is:

> Licensed under either of
>
>    Apache License, Version 2.0 (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)
>    MIT license (LICENSE-MIT or http://opensource.org/licenses/MIT)
>
> at your option.

Thanks!

Tim.

**Comment by dbrgn** [comment]
Hi. I'll add a license (Apache 2.0 / MIT) tonight, but note that I'm not actually sure if the driver crate is even finished :slightly_smiling_face: I'll check.

**Comment by dbrgn** [comment]
I just pushed a commit with the license. Feel free to test how much of this crate already works.

**Comment by tim-seoss** [comment]
OK, great thanks.  Temperature read seems to work (tested on stm32f103).
